
name: Buscar Ofertas e Publicar

on:
  schedule:
    - cron: '0 */6 * * *' # Executa a cada 6 horas
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install requests

      - name: Executar Automação
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python script_ofertas.py

      - name: Atualizar repositório (Landing Page)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add produtos.json
          git commit -m "Auto: Ofertas atualizadas" || exit 0
          git push
